from enum import IntEnum

class WalletWireCall(IntEnum):
    CREATE_ACTION = 1
    SIGN_ACTION = 2
    ABORT_ACTION = 3
    LIST_ACTIONS = 4
    INTERNALIZE_ACTION = 5
    LIST_OUTPUTS = 6
    RELINQUISH_OUTPUT = 7
    GET_PUBLIC_KEY = 8
    REVEAL_COUNTERPARTY_KEY_LINKAGE = 9
    REVEAL_SPECIFIC_KEY_LINKAGE = 10
    ENCRYPT = 11
    DECRYPT = 12
    CREATE_HMAC = 13
    VERIFY_HMAC = 14
    CREATE_SIGNATURE = 15
    VERIFY_SIGNATURE = 16
    ACQUIRE_CERTIFICATE = 17
    LIST_CERTIFICATES = 18
    PROVE_CERTIFICATE = 19
    RELINQUISH_CERTIFICATE = 20
    DISCOVER_BY_IDENTITY_KEY = 21
    DISCOVER_BY_ATTRIBUTES = 22
    IS_AUTHENTICATED = 23
    WAIT_FOR_AUTHENTICATION = 24
    GET_HEIGHT = 25
    GET_HEADER_FOR_HEIGHT = 26
    GET_NETWORK = 27
    GET_VERSION = 28
